package com.wylosowana.domain.answers;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.wylosowana.domain.answers.converters.ListOfSolutionConverter;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;
import java.util.List;

@ToString
@EqualsAndHashCode
@NoArgsConstructor
@DynamoDBTable(tableName = "SHOULD_BE_OVERRIDDEN")
public class Answer implements Serializable {
    public static final String ANSWER_TABLE_NAME = System.getenv("ANSWERS_TABLE_NAME");
    private static final long serialVersionUID = 471511275025144345L;

    private String id;
    private String testId;
    private String login;
    private String lang;
    private List<Solution> answers;
    private int points;
    private int maxPoints;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "testId")
    public String getTestId() {
        return testId;
    }

    @DynamoDBAttribute(attributeName = "login")
    public String getLogin() {
        return login;
    }

    @DynamoDBAttribute(attributeName = "lang")
    public String getLang() {
        return lang;
    }

    @DynamoDBAttribute(attributeName = "answers")
    @DynamoDBTypeConverted(converter = ListOfSolutionConverter.class)
    public List<Solution> getAnswers() {
        return answers;
    }

    @DynamoDBAttribute(attributeName = "points")
    public int getPoints() {
        return points;
    }

    @DynamoDBAttribute(attributeName = "maxPoints")
    public int getMaxPoints() {
        return maxPoints;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setTestId(String testId) {
        this.testId = testId;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    public void setAnswers(List<Solution> answers) {
        this.answers = answers;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public void setMaxPoints(int maxPoints) {
        this.maxPoints = maxPoints;
    }
}
