package wylosowana.model.Test;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import wylosowana.converters.LangConverter;

import java.util.List;

@DynamoDBTable(tableName = "Tests")
public class Test {
    private String id;
    private String title;
    private String language;
    private List<LangObject> langs;
    private List<String> candidateLogins;

    public Test(){ }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "testName")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute(attributeName = "language")
    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @DynamoDBAttribute(attributeName = "candidate_logins")
    public List<String> getCandidateLogins() {
        return candidateLogins;
    }

    public void setCandidateLogins(List<String> candidateLogins) {
        this.candidateLogins = candidateLogins;
    }


    @DynamoDBTypeConverted(converter = LangConverter.class)
    @DynamoDBAttribute(attributeName = "langs")
    public List<LangObject> getLangs() {
        return langs;
    }

    public void setLangs(List<LangObject> langs) {
        this.langs = langs;
    }

}
