package wylosowana.model.Test;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.ArrayList;
import java.util.List;

@DynamoDBTable(tableName = "Tests")
public class Test {
    private String id;
    private String testName;
    private ArrayList<LangObject> langs;
    private List<String> candidateLogins;

    public Test(){ }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "testName")
    public String getTestName() {
        return testName;
    }

    public void setTestName(String testName) {
        this.testName = testName;
    }

    @DynamoDBAttribute(attributeName = "candidateLogins")
    public List<String> getCandidateLogins() {
        return candidateLogins;
    }

    public void setCandidateLogins(List<String> candidateLogins) {
        this.candidateLogins = candidateLogins;
    }


    @DynamoDBAttribute(attributeName = "langs")
    public ArrayList<LangObject> getLangs() {
        return langs;
    }

    public void setLangs(ArrayList<LangObject> langs) {
        this.langs = langs;
    }

    public void addLang(LangObject langObject){
        langs.add(langObject);
    }

    public void addCandidate(String candidate){
        if(candidateLogins.stream().
                noneMatch(t -> t.equals(candidate))) {
            candidateLogins.add(candidate);
        }

    }

}
